image: elsa/ubu18-clang6:latest

stages:
  - compile
  - test

build-linux-gcc:
  stage: compile
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make
  tags:
    - linux
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - build/

build-linux-clang:
  stage: compile
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/clang++
    - make
  tags:
    - linux
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - build/

test-XOR:
  stage: test
  script:
    - python setup.py install --user
    - python XOR.py
  tags:
    - XOR
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - build/